### ISSUE TITLE
which() vs. index() vs. get_type_index()

### ISSUE THREAD

**Issue by joto** [mapbox/variant#67]
Our `variant` type has two functions giving access to the index of the currently used type:
* `which()` returns the 0-based index counting from the left
* `get_type_index()` returns the 0-based index counting from the right

So with `variant<int, std::string> v` these are true:
* `v{1}.which() == 0` and `v{1}.get_type_index() == 1`
* `v{"foo"}.which() == 1` and `v{1}.get_type_index() == 0`

Boost::variant only has the function `which()`, the upcoming standard calls this function `index()`.

All of this is confusing and error prone (as you can see in #65).

I suggest deprecating the `get_type_index()` function, maybe making it private. Having this strange counting-from-the-back is only a side-effect of the implementation as far as I can see, so it is not something the user should need to know. We can keep the `which()` function for compatibility with boost and maybe add the `index()` function as an alias. If the standard is actually adopted we can deprecate `which()` later.

Any opinions?

**Comment by artemp** [comment]
`operator<` is fixed in https://github.com/mapbox/variant/pull/65. I'm OK with making `get_type_index` private method.

**Comment by lightmare** [comment]
Rather than making it private, it might be best to just remove it. In the two comparison operators where it still appears it can easily be replaced with `index()`. In `dispatcher` and `binary_dispatcher` it should be replaced with `is`:
```c++
    VARIANT_INLINE static result_type apply(V & v, F f)
    {
        //if (v.get_type_index() == sizeof...(Types))
        if (v.is<T>)
        {
            return f(unwrapper<T>::apply(v. template get<T>()));
        }
        else
        {
            return dispatcher<F, V, R, Types...>::apply(v, f);
        }
    }
```

**Comment by artemp** [comment]
@lightmare - like it ^ !! Will apply, cheers!

**Comment by artemp** [comment]
Ok, good to remove `get_type_index` once we make
`invalid_type == sizeof(Types...) + 1` or other fix for
```c++
REQUIRE(variant_type{mapbox::util::no_init()}.get_type_index() == mapbox::util::detail::invalid_value);
```

**Comment by artemp** [comment]
closing, tracking this issue in #73
